export const BACKEND_URL = process.env.BACKEND_URL
export const BACKEND_SOCKET = process.env.BACKEND_SOCKET

export const TEST = 'TEST'

export const CHECK_SERVER_START = 'CHECK_SERVER_START'
export const CHECK_SERVER_END = 'CHECK_SERVER_END'
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED'
export const SOCKET_ERROR = 'SOCKET_ERROR'

export const STORE_CURRENT_TABS = 'STORE_CURRENT_TABS'
export const SEND_TABS = 'SEND_TABS'
export const SEND_TABS_OK = 'SEND_TABS_OK'

export const CHANGE_SELECT = 'CHANGE_SELECT'
export const CHANGE_SELECT_ALL = 'CHANGE_SELECT_ALL'
