export const TEST = 'TEST'

export const CHECK_SERVER_START = 'CHECK_SERVER_START'
export const CHECK_SERVER_END = 'CHECK_SERVER_END'
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED'
export const SOCKET_ERROR = 'SOCKET_ERROR'

export const STORE_CURRENT_TABS = 'STORE_CURRENT_TABS'
export const SEND_TABS = 'SEND_TABS'
export const SEND_TABS_OK = 'SEND_TABS_OK'

export const CHANGE_SELECT = 'CHANGE_SELECT'
export const CHANGE_SELECT_ALL = 'CHANGE_SELECT_ALL'

export const SETTINGS_CHECK = 'SETTINGS_CHECK'
export const SETTINGS_EDIT = 'SETTINGS_EDIT'
export const SETTINGS_EDIT_CANCEL = 'SETTINGS_EDIT_CANCEL'
